name: Upload to Wrike

defaults:
  run:
    working-directory: scripts/upload-to-wrike

on:
  schedule:
    - cron: 5 4 * * *
  workflow_dispatch:

jobs:
  upload-to-wrike:
    name: Upload to Wrike
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Install Deno
        uses: denoland/setup-deno@v2
      - name: Upload avvisi and FAQs
        run: deno --allow-env --allow-net --allow-read mod.ts
        env:
          DATOCMS_API_TOKEN: ${{ secrets.DATOCMS_API_TOKEN }}
          SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          WRIKE_ACCESS_TOKEN: ${{ secrets.WRIKE_ACCESS_TOKEN }}
          WRIKE_AVVISI_ATTACHMENT_FILENAME: ${{ vars.WRIKE_AVVISI_ATTACHMENT_FILENAME }}
          WRIKE_AVVISI_ATTACHMENT_ID: ${{ vars.WRIKE_AVVISI_ATTACHMENT_ID }}
          WRIKE_FAQ_ATTACHMENT_FILENAME: ${{ vars.WRIKE_FAQ_ATTACHMENT_FILENAME }}
          WRIKE_FAQ_ATTACHMENT_ID: ${{ vars.WRIKE_FAQ_ATTACHMENT_ID }}
          WRIKE_TASK_ID: ${{ vars.WRIKE_TASK_ID }}
          WRIKE_WORK_IN_PROGRESS_STATUS_ID: ${{ vars.WRIKE_WORK_IN_PROGRESS_STATUS_ID }}
